import type { NewDestination } from "./schema";

// 30 curated Indian destinations. budgetPerDay is INR for one mid-range
// traveller (stay + food + local transport + sightseeing). Hidden picks are
// less touristy alternatives.
export const seedDestinations: Omit<NewDestination, "id" | "createdAt">[] = [
  {
    slug: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    district: "Tirupati",
    category: "pilgrimage",
    shortDescription:
      "Sacred hill town home to the world's most-visited temple of Lord Venkateswara.",
    description:
      "Tirupati is one of the holiest sites in India. The Sri Venkateswara temple atop Tirumala hills draws millions of pilgrims each year. Plan early-morning darshan, visit Akasa Ganga, and stop by Sri Kalahasti nearby.",
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 95,
    latitude: "13.6288",
    longitude: "79.4192",
  },
  {
    slug: "hampi",
    name: "Hampi",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    shortDescription:
      "UNESCO ruins of the Vijayanagara empire spread across a surreal boulder-strewn landscape.",
    description:
      "Hampi's temple complexes, royal enclosures and bazaars cover 36 square kilometres. Climb Matanga Hill at dawn, coracle across the Tungabhadra, and explore Virupaksha and Vittala temples.",
    budgetPerDay: 1200,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "15.3350",
    longitude: "76.4600",
  },
  {
    slug: "munnar",
    name: "Munnar",
    state: "Kerala",
    district: "Idukki",
    category: "hill_station",
    shortDescription:
      "Rolling tea plantations, misty peaks and Anamudi — South India's highest.",
    description:
      "Munnar's tea estates carpet the Western Ghats. Hike to Echo Point, see the rare Neelakurinji bloom (every 12 years), tour Tata Tea Museum, and spot Nilgiri tahr at Eravikulam.",
    budgetPerDay: 2000,
    recommendedDays: 3,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 85,
    latitude: "10.0889",
    longitude: "77.0595",
  },
  {
    slug: "goa-north",
    name: "North Goa",
    state: "Goa",
    district: "North Goa",
    category: "beach",
    shortDescription:
      "Beach shacks, Portuguese churches and the famous nightlife of Baga and Anjuna.",
    description:
      "North Goa packs Calangute, Baga, Anjuna, Vagator and Morjim beaches into a short drive. Don't miss Saturday Night Market at Arpora and the Chapora fort sunset.",
    budgetPerDay: 2500,
    recommendedDays: 4,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "15.5527",
    longitude: "73.7517",
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    district: "Dehradun",
    category: "adventure",
    shortDescription:
      "Yoga capital on the Ganga — rafting, cliff jumping and Beatles-era ashrams.",
    description:
      "Rishikesh balances spirituality and adrenaline. Raft the Ganga grade III rapids, cross Lakshman Jhula, attend the Triveni Ghat aarti, and try a 3-day yoga retreat.",
    budgetPerDay: 1800,
    recommendedDays: 3,
    bestMonths: "Sep,Oct,Nov,Feb,Mar,Apr",
    isHidden: false,
    popularity: 88,
    latitude: "30.0869",
    longitude: "78.2676",
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    district: "Varanasi",
    category: "pilgrimage",
    shortDescription:
      "India's oldest living city — ghats, the Ganga aarti and labyrinthine lanes.",
    description:
      "Varanasi (Kashi) is sacred to Hindus. Take a dawn boat ride on the Ganga, witness the Ganga aarti at Dashashwamedh Ghat, visit Kashi Vishwanath, and walk through Sarnath where Buddha gave his first sermon.",
    budgetPerDay: 1000,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "25.3176",
    longitude: "82.9739",
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    shortDescription:
      "The Pink City — forts, palaces and bazaars from Rajasthan's royal past.",
    description:
      "Jaipur's Amber Fort, Hawa Mahal, City Palace and Jantar Mantar form the obvious circuit. Wander Johari and Bapu bazaars for block prints and bangles. Try dal-baati-churma at Chokhi Dhani.",
    budgetPerDay: 1500,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 92,
    latitude: "26.9124",
    longitude: "75.7873",
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    district: "Udaipur",
    category: "heritage",
    shortDescription:
      "City of Lakes — Lake Palace, ghats and the largest royal palace in Rajasthan.",
    description:
      "Udaipur centres on Lake Pichola. Take the sunset boat ride, tour the City Palace, see Jagdish Temple and visit Bagore-ki-Haveli for the evening folk performance.",
    budgetPerDay: 2200,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 89,
    latitude: "24.5854",
    longitude: "73.7125",
  },
  {
    slug: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "hill_station",
    shortDescription:
      "Gateway to Lahaul-Spiti, Solang valley adventures and Old Manali cafés.",
    description:
      "Manali sits on the Beas at 2050 m. Day-trip to Rohtang or Atal tunnel, paraglide at Solang, eat in Old Manali, and use it as the base for Spiti circuit.",
    budgetPerDay: 2200,
    recommendedDays: 4,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 88,
    latitude: "32.2396",
    longitude: "77.1887",
  },
  {
    slug: "ladakh-leh",
    name: "Leh-Ladakh",
    state: "Ladakh",
    district: "Leh",
    category: "adventure",
    shortDescription:
      "High-altitude desert of monasteries, blue lakes and the world's highest motorable passes.",
    description:
      "Ladakh demands a 2-day acclimatisation in Leh. From there: Pangong Tso, Nubra valley (Khardung La), Tso Moriri, and monasteries of Hemis, Thiksey, Diskit. Ride a Royal Enfield if you can.",
    budgetPerDay: 3500,
    recommendedDays: 7,
    bestMonths: "Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 90,
    latitude: "34.1526",
    longitude: "77.5770",
  },
  {
    slug: "andaman-havelock",
    name: "Havelock Island",
    state: "Andaman & Nicobar",
    district: "South Andaman",
    category: "beach",
    shortDescription:
      "Radhanagar Beach, scuba diving over coral, and the bluest water in India.",
    description:
      "Havelock (Swaraj Dweep) has Radhanagar (rated Asia's best beach) and Elephant Beach for snorkelling. Day-trip to Neil Island. Scuba operators run discover dives even for non-certified visitors.",
    budgetPerDay: 4000,
    recommendedDays: 5,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr,May",
    isHidden: false,
    popularity: 84,
    latitude: "12.0269",
    longitude: "92.9716",
  },
  {
    slug: "coorg",
    name: "Coorg (Madikeri)",
    state: "Karnataka",
    district: "Kodagu",
    category: "hill_station",
    shortDescription:
      "Coffee plantations, Abbey Falls, and Tibetan monasteries at Bylakuppe.",
    description:
      "Coorg is Karnataka's coffee country. Stay on a plantation, hike to Tadiandamol peak, visit Namdroling monastery, and watch sunset at Raja's Seat.",
    budgetPerDay: 1800,
    recommendedDays: 3,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 80,
    latitude: "12.4244",
    longitude: "75.7382",
  },
  {
    slug: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    district: "Nilgiris",
    category: "hill_station",
    shortDescription:
      "Queen of Nilgiris — tea estates, the toy train, and the Botanical Gardens.",
    description:
      "Take the Nilgiri Mountain Railway from Mettupalayam (UNESCO). Boat at Ooty Lake, drive to Doddabetta peak, and side-trip to Coonoor's quieter tea trails.",
    budgetPerDay: 1700,
    recommendedDays: 3,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 82,
    latitude: "11.4102",
    longitude: "76.6950",
  },
  {
    slug: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    district: "Chhatarpur",
    category: "heritage",
    shortDescription:
      "UNESCO temples of the Chandela dynasty famed for their intricate sculptures.",
    description:
      "Khajuraho's Western Group (Kandariya Mahadev, Lakshmana, Vishwanath) is the must-see; the Eastern and Southern groups are quieter. Pair with a Panna tiger safari nearby.",
    budgetPerDay: 1200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "24.8318",
    longitude: "79.9199",
  },
  {
    slug: "kaziranga",
    name: "Kaziranga",
    state: "Assam",
    district: "Golaghat",
    category: "wildlife",
    shortDescription:
      "World's largest population of one-horned rhinos in a UNESCO grassland park.",
    description:
      "Kaziranga has four ranges. Morning elephant safari in the Central (Kohora) range gives the best rhino sightings. Add jeep safaris in Western (Bagori) and Eastern (Agoratoli).",
    budgetPerDay: 2200,
    recommendedDays: 3,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 75,
    latitude: "26.5775",
    longitude: "93.1717",
  },
  {
    slug: "ranthambore",
    name: "Ranthambore",
    state: "Rajasthan",
    district: "Sawai Madhopur",
    category: "wildlife",
    shortDescription:
      "Rajasthan's best tiger reserve, with a hilltop fort inside the park.",
    description:
      "Ranthambore's Zones 3 and 4 are most reliable for tiger sightings. Book safaris in advance. The ancient Ranthambore fort and Trinetra Ganesh temple sit inside the reserve.",
    budgetPerDay: 2800,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 80,
    latitude: "26.0173",
    longitude: "76.5026",
  },
  {
    slug: "kanyakumari",
    name: "Kanyakumari",
    state: "Tamil Nadu",
    district: "Kanyakumari",
    category: "pilgrimage",
    shortDescription:
      "Southernmost tip of mainland India — sunrise and sunset over three seas.",
    description:
      "The Vivekananda Rock Memorial and Thiruvalluvar statue stand offshore. Watch sunrise from the beach and sunset from the Gandhi Memorial. Suchindram Sthanumalayan temple is a short drive.",
    budgetPerDay: 1200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 78,
    latitude: "8.0883",
    longitude: "77.5385",
  },
  {
    slug: "pondicherry",
    name: "Pondicherry",
    state: "Puducherry",
    district: "Puducherry",
    category: "beach",
    shortDescription:
      "French quarter cafés, Auroville and the Promenade Beach by the Bay of Bengal.",
    description:
      "Pondicherry's White Town has mustard buildings, bougainvillea and cafés. Visit Sri Aurobindo Ashram, ride to Auroville's Matrimandir, and end with a sea-facing dinner at La Maison Rose.",
    budgetPerDay: 1800,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 85,
    latitude: "11.9416",
    longitude: "79.8083",
  },
  {
    slug: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    district: "Darjeeling",
    category: "hill_station",
    shortDescription:
      "Tea, the Himalayan Railway and a sunrise over Kanchenjunga from Tiger Hill.",
    description:
      "Darjeeling rewards an early start at Tiger Hill for Kanchenjunga views, a toy-train ride, the Padmaja Naidu Zoo and Happy Valley tea estate. Pair with nearby Pelling or Gangtok.",
    budgetPerDay: 1800,
    recommendedDays: 3,
    bestMonths: "Mar,Apr,May,Sep,Oct,Nov",
    isHidden: false,
    popularity: 82,
    latitude: "27.0360",
    longitude: "88.2627",
  },
  {
    slug: "auli",
    name: "Auli",
    state: "Uttarakhand",
    district: "Chamoli",
    category: "adventure",
    shortDescription:
      "India's best ski slopes with a front-row view of Nanda Devi.",
    description:
      "Auli's slopes run between 2500 and 3050 m. Take the cable car from Joshimath (Asia's longest), ski Jan–Mar, and hike to Gurso Bugyal in summer.",
    budgetPerDay: 2200,
    recommendedDays: 3,
    bestMonths: "Jan,Feb,Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 65,
    latitude: "30.5260",
    longitude: "79.5640",
  },
  {
    slug: "spiti",
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    district: "Lahaul-Spiti",
    category: "adventure",
    shortDescription:
      "High-altitude cold desert — Key Monastery, Chandratal lake and the world's highest village.",
    description:
      "Spiti's loop covers Kaza, Key, Komic (world's highest motorable village), Hikkim post office, Langza fossil village and Chandratal. Best done by road from Manali (summer only) or via Kinnaur (year-round).",
    budgetPerDay: 2500,
    recommendedDays: 7,
    bestMonths: "Jun,Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 60,
    latitude: "32.2462",
    longitude: "78.0349",
  },
  {
    slug: "gokarna",
    name: "Gokarna",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    shortDescription:
      "A quieter, hippie-leaning alternative to Goa with five crescent beaches.",
    description:
      "Walk the beach trek from Kudle to Om to Half Moon to Paradise. Visit the Mahabaleshwar temple in town. Stay in beach-shack huts on Kudle.",
    budgetPerDay: 1500,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 65,
    latitude: "14.5479",
    longitude: "74.3188",
  },
  {
    slug: "tawang",
    name: "Tawang",
    state: "Arunachal Pradesh",
    district: "Tawang",
    category: "adventure",
    shortDescription:
      "Largest monastery in India, snow-fed lakes and the high Sela pass.",
    description:
      "Tawang Monastery is the 17th-century seat of Buddhism in Arunachal. Cross Sela pass (4170 m), see Madhuri Lake and Bumla pass at the Chinese border (permit required).",
    budgetPerDay: 2800,
    recommendedDays: 5,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 55,
    latitude: "27.5860",
    longitude: "91.8597",
  },
  {
    slug: "majuli",
    name: "Majuli",
    state: "Assam",
    district: "Majuli",
    category: "heritage",
    shortDescription:
      "World's largest river island — Vaishnavite satras, mask-making and bamboo huts.",
    description:
      "Ferry from Jorhat. Stay in a bamboo cottage. Visit Kamalabari, Auniati and Samaguri satras, watch a Bhaona performance, and meet Hem Chandra Goswami's mask-making workshop.",
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 50,
    latitude: "26.9526",
    longitude: "94.1660",
  },
  {
    slug: "chettinad",
    name: "Chettinad",
    state: "Tamil Nadu",
    district: "Sivaganga",
    category: "heritage",
    shortDescription:
      "Faded merchant mansions, Athangudi tiles and the spiciest cuisine in the south.",
    description:
      "Karaikudi is the heart of Chettinad. Tour heritage homes (Chettiar mansions), watch Athangudi tile-making and Kandangi sari weaving, and book a Chettinad cooking class.",
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 55,
    latitude: "10.0667",
    longitude: "78.7833",
  },
  {
    slug: "dholavira",
    name: "Dholavira",
    state: "Gujarat",
    district: "Kutch",
    category: "heritage",
    shortDescription:
      "UNESCO Harappan city in the Great Rann of Kutch — 4500 years of urban planning.",
    description:
      "Dholavira's stepped reservoirs, citadel and signboard are among the best-preserved Harappan ruins. Combine with the white desert and Tent City of Rann Utsav (Nov–Feb).",
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 45,
    latitude: "23.8898",
    longitude: "70.2089",
  },
  {
    slug: "mussoorie",
    name: "Mussoorie",
    state: "Uttarakhand",
    district: "Dehradun",
    category: "hill_station",
    shortDescription:
      "Queen of the Hills — Mall Road, Kempty Falls and views of the Doon valley.",
    description:
      "Walk the Mall Road, ride the cable car to Gun Hill, see Kempty and Bhatta falls, and side-trip to Landour for old-Mussoorie cafés.",
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 80,
    latitude: "30.4598",
    longitude: "78.0664",
  },
  {
    slug: "mahabaleshwar",
    name: "Mahabaleshwar",
    state: "Maharashtra",
    district: "Satara",
    category: "hill_station",
    shortDescription:
      "Strawberry country in the Sahyadris — Arthur's Seat, Venna Lake and Pratapgad fort.",
    description:
      "Mahabaleshwar peaks at 1438 m. Watch sunrise at Wilson Point, sunset at Bombay Point, boat at Venna Lake, and pick strawberries Nov–Mar. Pratapgad fort is a 25 km drive.",
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 78,
    latitude: "17.9220",
    longitude: "73.6580",
  },
  {
    slug: "shirdi",
    name: "Shirdi",
    state: "Maharashtra",
    district: "Ahmednagar",
    category: "pilgrimage",
    shortDescription:
      "Home of Sai Baba — the Samadhi Mandir is the centre of the temple complex.",
    description:
      "Plan early-morning Kakad Aarti darshan. The Samadhi Mandir, Dwarkamai mosque, Chavadi and Lendi Baug make the core circuit. Shani Shingnapur is a 70 km add-on.",
    budgetPerDay: 1200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 88,
    latitude: "19.7669",
    longitude: "74.4773",
  },
  {
    slug: "bodh-gaya",
    name: "Bodh Gaya",
    state: "Bihar",
    district: "Gaya",
    category: "pilgrimage",
    shortDescription:
      "Where the Buddha attained enlightenment under the Bodhi tree — UNESCO Mahabodhi temple.",
    description:
      "The Mahabodhi temple and its descendant Bodhi tree are the centre. Monasteries from every Buddhist country circle the complex. Visit the 80-foot Great Buddha statue and Sujata Stupa.",
    budgetPerDay: 1000,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "24.6961",
    longitude: "84.9919",
  },
];
