import type { NewNearbyDestination } from "./schema";

// 20 one-day-trip spots from Bangalore (BLR center: 12.9716, 77.5946).
// distanceKm and drivingMinutes are one-way estimates assuming normal traffic.
export const bangaloreOneDayTrips: Omit<
  NewNearbyDestination,
  "id" | "createdAt"
>[] = [
  {
    slug: "blr-nandi-hills",
    name: "Nandi Hills",
    baseCity: "Bangalore",
    category: "hill_station",
    shortDescription:
      "Sunrise viewpoint and trekking spot at 1478 m, an hour north of the city.",
    description:
      "Nandi Hills (Nandi Betta) is the classic Bangalore sunrise drive. Leave by 4 am to reach the summit before 6. Walk to Tipu's Drop, Nehru Nilaya, the Bhoga Nandeeshwara temple at the base and the 4 km hilltop loop. Carry layers — it gets cold pre-sunrise.",
    distanceKm: 60,
    drivingMinutes: 90,
    entryFeePerPerson: 30,
    idealHoursAtPlace: 3,
    bestStartTime: "04:30",
    highlights: "Sunrise,Tipu's Drop,Bhoga Nandeeshwara temple,Paragliding",
    latitude: "13.3702",
    longitude: "77.6835",
    popularity: 95,
  },
  {
    slug: "blr-skandagiri",
    name: "Skandagiri",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Night-trek hill with cloud-walk views above Nandi Hills.",
    description:
      "Skandagiri (Kalavara Durga) is a 1450 m hill known for cloud-cover views and the ruined fort at the top. The official night trek was closed for a while; check the latest rules. Day-trek up the eastern face takes 2 hours.",
    distanceKm: 70,
    drivingMinutes: 105,
    entryFeePerPerson: 250,
    idealHoursAtPlace: 5,
    bestStartTime: "05:00",
    highlights: "Hill trek,Sea of clouds (monsoon),Fort ruins",
    latitude: "13.4671",
    longitude: "77.8108",
    popularity: 78,
  },
  {
    slug: "blr-bannerghatta",
    name: "Bannerghatta National Park",
    baseCity: "Bangalore",
    category: "wildlife",
    shortDescription:
      "Safari, zoo, butterfly park — a 45-minute drive from south Bangalore.",
    description:
      "Bannerghatta combines a zoo, a butterfly park and a safari bus through tiger, lion, bear and herbivore enclosures. Book the safari online to skip the queue. Plan 4 hours.",
    distanceKm: 22,
    drivingMinutes: 50,
    entryFeePerPerson: 400,
    idealHoursAtPlace: 4,
    bestStartTime: "09:00",
    highlights: "Tiger & lion safari,Butterfly park,Bear sanctuary",
    latitude: "12.7993",
    longitude: "77.5773",
    popularity: 90,
  },
  {
    slug: "blr-shivanasamudra",
    name: "Shivanasamudra Falls",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Twin segmented falls on the Kaveri — Gaganachukki and Bharachukki.",
    description:
      "Shivanasamudra splits the Kaveri into two cataracts. Bharachukki is the more accessible side with viewpoint stairs and coracle rides at the bottom (Aug–Nov flow is best). Stop at Talakadu en route if time allows.",
    distanceKm: 135,
    drivingMinutes: 180,
    entryFeePerPerson: 10,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Bharachukki falls,Coracle ride,Talakadu detour",
    latitude: "12.3014",
    longitude: "77.1733",
    popularity: 82,
  },
  {
    slug: "blr-ramanagara",
    name: "Ramanagara",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "The rocky hills where Sholay was shot — climbing, rappelling, silk town.",
    description:
      "Ramanagara's monolithic granite hills are India's bouldering capital. Hike Ramadevara Betta (the Sholay rocks) and the Jatayu vulture sanctuary. The town also runs Asia's largest silk cocoon market.",
    distanceKm: 50,
    drivingMinutes: 75,
    entryFeePerPerson: 100,
    idealHoursAtPlace: 4,
    bestStartTime: "06:30",
    highlights: "Bouldering,Ramadevara Betta hike,Silk market",
    latitude: "12.7195",
    longitude: "77.2814",
    popularity: 75,
  },
  {
    slug: "blr-savandurga",
    name: "Savandurga",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Asia's largest monolith — a steep granite trek with sweeping views.",
    description:
      "Savandurga is a single 1226 m granite dome. The Karigudda (Black Hill) trek takes about 2 hours up the bare rock — no shade, so start before 7 am. Bilegudda (White Hill) is rarely permitted.",
    distanceKm: 60,
    drivingMinutes: 90,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 5,
    bestStartTime: "05:30",
    highlights: "Granite monolith trek,Lakshmi Narasimha temple,Manchanabele dam nearby",
    latitude: "12.9182",
    longitude: "77.2974",
    popularity: 80,
  },
  {
    slug: "blr-anthargange",
    name: "Anthargange",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Cave trek through volcanic boulder formations near Kolar.",
    description:
      "Anthargange means 'inner Ganges' — a hill with caves formed by volcanic boulders and a perennial spring at the Kashi Vishweshwara temple. Best as a guided night trek; carry a torch for the cave sections.",
    distanceKm: 70,
    drivingMinutes: 100,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 4,
    bestStartTime: "06:00",
    highlights: "Cave trek,Boulder hopping,Kashi Vishweshwara temple",
    latitude: "13.1635",
    longitude: "78.1488",
    popularity: 72,
  },
  {
    slug: "blr-bheemeshwari",
    name: "Bheemeshwari",
    baseCity: "Bangalore",
    category: "wildlife",
    shortDescription:
      "Jungle Lodges resort on the Kaveri — coracle, mahseer fishing, river walks.",
    description:
      "Bheemeshwari is a Jungle Lodges & Resorts property on the Kaveri inside the Cauvery Wildlife Sanctuary. Coracle rides, jet skis, kayaking, and a chance to spot mahseer, otters and crocodiles. Book the day-package in advance.",
    distanceKm: 110,
    drivingMinutes: 150,
    entryFeePerPerson: 1500,
    idealHoursAtPlace: 5,
    bestStartTime: "07:00",
    highlights: "Coracle,Kayaking,Mahseer fishing,Birdwatching",
    latitude: "12.4250",
    longitude: "77.2367",
    popularity: 70,
  },
  {
    slug: "blr-mekedatu",
    name: "Mekedatu & Sangama",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Where the Kaveri narrows to a goat's leap — coracles at Sangama, gorge at Mekedatu.",
    description:
      "Sangama is the confluence of the Kaveri and Arkavathi; cross the river by coracle to reach Mekedatu where the Kaveri funnels through a 3 m gorge. Avoid monsoon — the bus and coracle are often suspended.",
    distanceKm: 90,
    drivingMinutes: 135,
    entryFeePerPerson: 50,
    idealHoursAtPlace: 4,
    bestStartTime: "06:30",
    highlights: "Sangama coracle,Mekedatu gorge,Picnic spot",
    latitude: "12.3000",
    longitude: "77.4500",
    popularity: 78,
  },
  {
    slug: "blr-big-banyan-tree",
    name: "Dodda Aalada Mara (Big Banyan Tree)",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription:
      "A 400-year-old banyan spread over three acres — a quick half-day picnic.",
    description:
      "The original tree's central trunk decayed in the 1900s, but its aerial roots have spread into what looks like a forest. Easy half-day with kids. Combine with Manchanabele dam or Big Tree Country club nearby.",
    distanceKm: 28,
    drivingMinutes: 55,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 1,
    bestStartTime: "08:00",
    highlights: "400-year banyan,Picnic ground,Photography",
    latitude: "12.8730",
    longitude: "77.3717",
    popularity: 68,
  },
  {
    slug: "blr-manchanabele",
    name: "Manchanabele Dam",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Reservoir on the Arkavathi for kayaking and stand-up paddle.",
    description:
      "Manchanabele is the quieter alternative to Sangama. Multiple operators run kayaking and SUP sessions here. Pair it with Savandurga or Big Banyan Tree for a full day.",
    distanceKm: 40,
    drivingMinutes: 75,
    entryFeePerPerson: 600,
    idealHoursAtPlace: 3,
    bestStartTime: "07:00",
    highlights: "Kayaking,Stand-up paddle,Sunset view",
    latitude: "12.9145",
    longitude: "77.3739",
    popularity: 70,
  },
  {
    slug: "blr-channapatna",
    name: "Channapatna",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription:
      "India's toy town — GI-tagged lacquered wooden toys, workshops to watch.",
    description:
      "Channapatna's wooden toys carry a GI tag. Most workshops welcome visitors to watch the lathe + lac process. Stop at Maya Organic and Varnam for ethically sourced toys. Channapatna town is also famous for sweet jaggery payasam.",
    distanceKm: 60,
    drivingMinutes: 90,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "08:30",
    highlights: "Toy workshops,Maya Organic,Lacquer demos",
    latitude: "12.6516",
    longitude: "77.2068",
    popularity: 68,
  },
  {
    slug: "blr-ghati-subramanya",
    name: "Ghati Subramanya",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription:
      "Cave temple to Subramanya and Lakshmi Narasimha, an hour north.",
    description:
      "Ghati Subramanya is built around a natural cave where Subramanya and Lakshmi Narasimha face opposite directions. Pair with Devarayanadurga for a temple-hopping day.",
    distanceKm: 60,
    drivingMinutes: 90,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Cave temple,Naga puja,Quiet hillside",
    latitude: "13.3833",
    longitude: "77.3833",
    popularity: 60,
  },
  {
    slug: "blr-devarayanadurga",
    name: "Devarayanadurga",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription:
      "Twin temples on a rocky hill — Yoga and Bhoga Narasimha — near Tumakuru.",
    description:
      "Devarayanadurga has two hilltop temples reached by long flights of steps. Namada Chilume, said to be the source of the Jayamangali, is a 4 km drive away. Mornings are cool and quiet.",
    distanceKm: 75,
    drivingMinutes: 110,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "07:00",
    highlights: "Yoga Narasimha,Bhoga Narasimha,Namada Chilume spring",
    latitude: "13.3667",
    longitude: "77.1833",
    popularity: 65,
  },
  {
    slug: "blr-pearl-valley",
    name: "Muthyala Maduvu (Pearl Valley)",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "A 92 m waterfall and Krishna temple tucked in the hills near Anekal.",
    description:
      "Pearl Valley is a short hike down to a seasonal waterfall — best after the monsoon. The Sri Madhava Swamy temple sits at the top. Add Bannerghatta or Kaivara on the same trip.",
    distanceKm: 40,
    drivingMinutes: 80,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "08:00",
    highlights: "Seasonal waterfall,Krishna temple,Short hike",
    latitude: "12.6500",
    longitude: "77.7833",
    popularity: 62,
  },
  {
    slug: "blr-janapada-loka",
    name: "Janapada Loka",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription:
      "Karnataka's folk-arts museum — puppet stage, masks, instruments, leather.",
    description:
      "Janapada Loka on the Mysore highway is the best folk-art museum in the state. Don't miss the Chitra Mantapa puppets, the Lokamatha mandira, and the live Yakshagana performances on Sundays.",
    distanceKm: 50,
    drivingMinutes: 75,
    entryFeePerPerson: 50,
    idealHoursAtPlace: 2,
    bestStartTime: "09:00",
    highlights: "Folk art museum,Puppet stage,Yakshagana (Sundays)",
    latitude: "12.7050",
    longitude: "77.2517",
    popularity: 60,
  },
  {
    slug: "blr-avalabetta",
    name: "Avalabetta",
    baseCity: "Bangalore",
    category: "hill_station",
    shortDescription:
      "Quiet cliff-edge viewpoint near Chickballapur with a cantilever skywalk.",
    description:
      "Avalabetta is the less crowded alternative to Nandi Hills. A short hike to the cliff-top temple is followed by a cantilever viewpoint over the valley. Combine with Lepakshi for a full day.",
    distanceKm: 90,
    drivingMinutes: 135,
    entryFeePerPerson: 50,
    idealHoursAtPlace: 2,
    bestStartTime: "06:00",
    highlights: "Cliff skywalk,Quiet viewpoint,Photography",
    latitude: "13.6300",
    longitude: "77.7867",
    popularity: 65,
  },
  {
    slug: "blr-lepakshi",
    name: "Lepakshi",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription:
      "16th-century Veerabhadra temple with the hanging pillar and a giant Nandi.",
    description:
      "Lepakshi (in Andhra Pradesh, 130 km north) has the Vijayanagara-era Veerabhadra temple, famed for its hanging pillar, ceiling frescoes and the largest monolithic Nandi in India. Pair with Avalabetta on the way back.",
    distanceKm: 130,
    drivingMinutes: 170,
    entryFeePerPerson: 25,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Hanging pillar,Veerabhadra temple,Monolithic Nandi",
    latitude: "13.8094",
    longitude: "77.6052",
    popularity: 75,
  },
  {
    slug: "blr-talakadu",
    name: "Talakadu",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription:
      "Buried temples on the Kaveri — Panchalinga darshana every 12 years.",
    description:
      "Talakadu is a sand-buried Ganga-era temple town on the Kaveri. Walk between the partially excavated Vaidyanatheshwara and Pataleshwara temples. Combine with Shivanasamudra falls or Somnathpur (Hoysala temple).",
    distanceKm: 140,
    drivingMinutes: 180,
    entryFeePerPerson: 10,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Buried temples,Kaveri ghat,Somnathpur add-on",
    latitude: "12.1894",
    longitude: "77.0231",
    popularity: 68,
  },
  {
    slug: "blr-kanva-reservoir",
    name: "Kanva Reservoir",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription:
      "Quiet reservoir near Channapatna for picnics and a half-day escape.",
    description:
      "Kanva (or Kanwa) is a peaceful reservoir off the Mysore highway. Boating is sometimes available; otherwise it's a calm picnic spot. Combine with Channapatna or Janapada Loka.",
    distanceKm: 60,
    drivingMinutes: 90,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "08:00",
    highlights: "Reservoir picnic,Birdwatching,Quiet drive",
    latitude: "12.7100",
    longitude: "77.1633",
    popularity: 55,
  },
];
