import type { NewCityPlace } from "./schema";

// Additional ~160 Bengaluru places to take the curated catalogue past 200.
// Compact format — short fields, accurate-as-best lat/lng and hours from
// general knowledge of these public landmarks. Where exact entry fees are
// not commonly published, we use realistic mid-range estimates.
//
// Schema reminder: kind ∈ attraction | temple | museum | park | lake |
// restaurant | mall | nightlife | market | viewpoint | church.

type T = Omit<NewCityPlace, "id" | "createdAt">;

// Helpers to keep each entry to ~5 lines.
function place(
  slug: string,
  name: string,
  kind: string,
  category: string,
  area: string,
  lat: string,
  lng: string,
  shortDescription: string,
  description: string,
  extras: Partial<T> = {}
): T {
  return {
    slug,
    name,
    city: "Bangalore",
    kind,
    category,
    area,
    description,
    shortDescription,
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 45,
    openTime: "09:00",
    closeTime: "21:00",
    openDays: "All",
    latitude: lat,
    longitude: lng,
    popularity: 60,
    avgCostForTwo: null,
    imageUrl: null,
    tags: null,
    googlePlaceId: null,
    ...extras,
  };
}

export const bangaloreCityPlacesExtra: T[] = [
  // ─────────── Temples (25 more) ───────────
  place(
    "blr-isckon-vaikuntha",
    "ISKCON Vaikuntha Hill",
    "temple",
    "spiritual",
    "Vasanthapura",
    "12.8731",
    "77.5535",
    "Newer ISKCON complex on a south Bangalore hill.",
    "ISKCON's second Bangalore campus, built on a hillside in Vasanthapura with an elaborate gopuram and Govinda's restaurant.",
    { idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "20:30", popularity: 75 }
  ),
  place(
    "blr-shiva-mandir-kemp-fort",
    "Shiv Mandir (Kemp Fort)",
    "temple",
    "spiritual",
    "Old Airport Road",
    "12.9594",
    "77.6480",
    "20-metre Shiva statue and underground walkthrough of pilgrimage replicas.",
    "Famous for its 65-foot Shiva statue and the simulated pilgrimage circuit beneath the temple — Amarnath, Kashi Vishwanath, Kedarnath and more.",
    { entryFeePerPerson: 30, idealMinutesAtPlace: 60, openTime: "07:00", closeTime: "21:00", popularity: 80 }
  ),
  place(
    "blr-sai-baba-malleshwaram",
    "Sai Baba Mandir Malleshwaram",
    "temple",
    "spiritual",
    "Malleshwaram",
    "13.0009",
    "77.5687",
    "Quiet Sai Baba shrine in old Malleshwaram.",
    "Regular bhajans and Thursday aartis draw the Malleshwaram crowd.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "21:00", popularity: 65 }
  ),
  place(
    "blr-shanmukha-temple-rrn",
    "Shanmukha Temple",
    "temple",
    "spiritual",
    "Rajarajeshwari Nagar",
    "12.9219",
    "77.5188",
    "Six-faced Subramanya shrine on a small hillock.",
    "Climb the steps for the Murugan idol; Tuesdays and full-moon days draw the biggest crowds.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "20:00", popularity: 65 }
  ),
  place(
    "blr-omkar-hills",
    "Omkar Hills",
    "temple",
    "spiritual",
    "Banashankari",
    "12.9000",
    "77.5000",
    "Hilltop ashram-temple with a 11-foot Om Shiva idol.",
    "Built by the late Sri Sri Omkarananda Saraswati Swamiji. Drive up the hill for sunset darshan plus panoramic city views.",
    { idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "20:00", popularity: 60 }
  ),
  place(
    "blr-mukthi-naga-temple",
    "Mukthi Naga Temple",
    "temple",
    "spiritual",
    "Ramohalli",
    "12.9300",
    "77.4500",
    "Open-air temple to Naga (serpent) deities surrounded by 11 lakh Naga idols.",
    "A Naga Prathishta (snake-deity offering) site, with thousands of stone Naga idols placed in concentric rings around the main shrine.",
    { entryFeePerPerson: 25, idealMinutesAtPlace: 45, openTime: "07:00", closeTime: "19:00", popularity: 60 }
  ),
  place(
    "blr-meenakshi-bannerghatta",
    "Meenakshi Sundareshwarar Temple",
    "temple",
    "spiritual",
    "Bannerghatta Road",
    "12.8856",
    "77.5963",
    "Modern Madurai-style temple on Bannerghatta Road.",
    "Built in the architectural style of the Madurai Meenakshi temple. Visit at dawn or dusk for the lighting.",
    { idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "20:30", popularity: 65 }
  ),
  place(
    "blr-prasanna-krishna-malleshwaram",
    "Sri Prasanna Krishna Swamy Temple",
    "temple",
    "spiritual",
    "Malleshwaram",
    "13.0036",
    "77.5675",
    "Old Krishna shrine off Sampige Road.",
    "Krishna Janmashtami here is a neighbourhood-wide festival.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "21:00", popularity: 55 }
  ),
  place(
    "blr-venkateshwara-malleshwaram",
    "Sri Venkateshwara Swamy Temple",
    "temple",
    "spiritual",
    "Malleshwaram",
    "13.0040",
    "77.5701",
    "Tirupati-styled Balaji shrine in central Malleshwaram.",
    "Brahmotsavam in the month of Aippasi sees large processions on 11th Cross.",
    { idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "21:00", popularity: 70 }
  ),
  place(
    "blr-kote-venkataramana",
    "Kote Venkataramana Temple",
    "temple",
    "spiritual",
    "KR Market",
    "12.9614",
    "77.5773",
    "Vijayanagara-era Vishnu temple beside Tipu's palace.",
    "Built around 1690 by Chikka Devaraja Wodeyar. Carved pillars and a green-and-gold Garuda gopuram.",
    { idealMinutesAtPlace: 30, openTime: "06:30", closeTime: "20:30", popularity: 65 }
  ),
  place(
    "blr-maha-bodhi-society",
    "Maha Bodhi Society",
    "temple",
    "spiritual",
    "Gandhinagar",
    "12.9778",
    "77.5904",
    "Buddhist centre with a Bodh-Gaya-style stupa.",
    "Replica of Mahabodhi temple housing Buddha relics. Daily Theravada chanting and meditation classes.",
    { idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "20:00", popularity: 60 }
  ),
  place(
    "blr-ramakrishna-math",
    "Ramakrishna Math (Basavanagudi)",
    "temple",
    "spiritual",
    "Basavanagudi",
    "12.9444",
    "77.5732",
    "Sri Ramakrishna's mission centre — universal hall and library.",
    "Quiet, plant-filled garden. Discourses on Vedanta and meditation classes most evenings.",
    { idealMinutesAtPlace: 45, openTime: "05:30", closeTime: "20:30", popularity: 70 }
  ),
  place(
    "blr-pyramid-valley",
    "Pyramid Valley International",
    "temple",
    "spiritual",
    "Kanakapura Road",
    "12.7320",
    "77.4830",
    "Meditation centre with a 50,000-sqft pyramid.",
    "The Maitreya Buddha Pyramid is the world's largest meditation pyramid by capacity. Free day visits plus retreats.",
    { idealMinutesAtPlace: 120, openTime: "06:00", closeTime: "20:00", popularity: 70 }
  ),
  place(
    "blr-art-of-living",
    "Art of Living International Centre",
    "temple",
    "spiritual",
    "Udayapura, Kanakapura Road",
    "12.7700",
    "77.5099",
    "Sri Sri Ravi Shankar's 65-acre ashram on a hill.",
    "Vishalakshi Mantap, Sumeru Mandapam, lotus ponds. Day visits welcome; courses run year-round.",
    { idealMinutesAtPlace: 150, openTime: "06:00", closeTime: "19:00", popularity: 75 }
  ),
  place(
    "blr-chokkanathaswamy-domlur",
    "Chokkanathaswamy Temple",
    "temple",
    "spiritual",
    "Domlur",
    "12.9620",
    "77.6383",
    "10th-century Chola temple, the oldest in Bengaluru.",
    "Modest structure but historically the city's oldest surviving temple. Inscriptions on the inner walls.",
    { idealMinutesAtPlace: 30, openTime: "06:30", closeTime: "20:00", popularity: 65 }
  ),
  place(
    "blr-suryanarayana-domlur",
    "Sri Suryanarayana Swamy Temple",
    "temple",
    "spiritual",
    "Domlur",
    "12.9614",
    "77.6371",
    "Sun-god temple — popular for Sunday surya namaskar puja.",
    "Sun-facing sanctum lit by morning rays. Sunday Surya Namaskar is the standout ritual.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "20:00", popularity: 55 }
  ),
  place(
    "blr-dharmaraya-swamy",
    "Sri Dharmaraya Swamy Temple",
    "temple",
    "spiritual",
    "Thigalarapet (KR Market)",
    "12.9663",
    "77.5773",
    "Pandava-deity temple, host of the iconic Karaga festival.",
    "9th-century shrine to the five Pandavas and Draupadi. The annual Karaga (March-April) is Bengaluru's most spectacular street procession.",
    { idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "21:00", popularity: 80 }
  ),
  place(
    "blr-karanji-anjaneya",
    "Karanji Anjaneya Temple",
    "temple",
    "spiritual",
    "Basavanagudi",
    "12.9412",
    "77.5701",
    "Massive Hanuman idol — Saturday Hanuman Chalisa draws crowds.",
    "18-foot stone Hanuman statue. Saturdays see continuous Chalisa group recital.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "21:00", popularity: 70 }
  ),
  place(
    "blr-panchamukhi-ganesha",
    "Panchamukhi Ganesha Temple",
    "temple",
    "spiritual",
    "Vidyaranyapura",
    "13.0741",
    "77.5631",
    "Five-faced Ganesha shrine — a relatively rare iconography.",
    "Built around a five-faced (panchamukhi) Ganesha idol. Sankashti Chaturthi sees long queues.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "21:00", popularity: 60 }
  ),
  place(
    "blr-shambhulingeshwara-cave",
    "Shambhulingeshwara Cave Temple",
    "temple",
    "spiritual",
    "Hesaraghatta",
    "13.1300",
    "77.4900",
    "Quiet cave shrine on the Hesaraghatta plateau.",
    "A natural cave-cum-temple. Sparsely visited, ideal for a meditative side trip on the way to Hesaraghatta lake.",
    { idealMinutesAtPlace: 30, openTime: "07:00", closeTime: "19:00", popularity: 50 }
  ),
  place(
    "blr-chikka-tirupati",
    "Chikka Tirupati",
    "temple",
    "spiritual",
    "Sarjapur (outskirts)",
    "12.8911",
    "77.8633",
    "'Little Tirupati' — Vishnu temple ~45 km east of city.",
    "Said to be the spot where Lord Venkateswara rested before reaching Tirumala. The Brahmotsavam in November is the major draw.",
    { idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "20:00", popularity: 70 }
  ),
  place(
    "blr-isha-foundation-blr",
    "Linga Bhairavi Devi Sannidhi",
    "temple",
    "spiritual",
    "Singasandra",
    "12.8714",
    "77.6322",
    "Isha Foundation's Linga Bhairavi consecration in south Bangalore.",
    "An open-to-all shrine of Linga Bhairavi. Twice-daily aartis and weekend offerings.",
    { idealMinutesAtPlace: 45, openTime: "07:00", closeTime: "20:00", popularity: 65 }
  ),
  place(
    "blr-kaadu-mallikarjuna",
    "Kaadu Mallikarjuna Swamy Temple",
    "temple",
    "spiritual",
    "Mallathahalli",
    "12.9750",
    "77.4980",
    "Old Shiva temple at Bangalore University's outskirts.",
    "A small Mallikarjuna shrine surrounded by tamarind groves. Maha Shivaratri draws steady crowds.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "20:30", popularity: 55 }
  ),
  place(
    "blr-veera-anjaneya",
    "Veera Anjaneya Swamy Temple",
    "temple",
    "spiritual",
    "Mahalakshmipuram",
    "13.0114",
    "77.5476",
    "Hanuman temple with daily Hanuman Chalisa parayana.",
    "Mahalakshmipuram's Saturday Hanuman magnet. Reasonably small but popular with families.",
    { idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "21:00", popularity: 55 }
  ),

  // ─────────── Restaurants & cafes (25 more) ───────────
  place(
    "blr-empire-mosque-road",
    "Empire Restaurant — Mosque Road",
    "restaurant",
    "food",
    "Frazer Town",
    "13.0024",
    "77.6118",
    "Bengaluru's most famous late-night kebabs and biryani chain — Mosque Road flagship.",
    "Beef kebab roll, kerala porotta with chicken-65, mutton biryani. Open till midnight, especially busy during Ramadan.",
    { avgCostForTwo: 600, idealMinutesAtPlace: 60, openTime: "11:00", closeTime: "01:00", popularity: 92 }
  ),
  place(
    "blr-meghana-old-airport",
    "Meghana Foods — Old Airport Road",
    "restaurant",
    "food",
    "Domlur",
    "12.9594",
    "77.6437",
    "Andhra biryani — the east-Bangalore office crowd's lunch destination.",
    "Boneless chicken biryani is the bestseller. Long lunch queues 1-2 pm on weekdays.",
    { avgCostForTwo: 800, idealMinutesAtPlace: 60, openTime: "11:30", closeTime: "23:30", popularity: 93 }
  ),
  place(
    "blr-truffles-st-marks",
    "Truffles — St Mark's Road",
    "restaurant",
    "food",
    "St Mark's Road",
    "12.9720",
    "77.5964",
    "Burgers, shakes and a relaxed central-Bangalore spot.",
    "The CBD outlet of the Truffles burger chain. Famous for the Cheese Beast and Sticky-date pudding.",
    { avgCostForTwo: 1100, idealMinutesAtPlace: 75, openTime: "11:30", closeTime: "23:00", popularity: 88 }
  ),
  place(
    "blr-burma-burma",
    "Burma Burma",
    "restaurant",
    "food",
    "Indiranagar 100 Feet Road",
    "12.9783",
    "77.6404",
    "Vegetarian Burmese tea-room — khow suey, samosa salad, kyaukswe.",
    "All-veg modern Burmese. Highlights: oh-no khow suey, tea-leaf salad, falooda kyaukswe. Loose-leaf tea menu.",
    { avgCostForTwo: 1800, idealMinutesAtPlace: 90, openTime: "12:00", closeTime: "23:00", popularity: 90 }
  ),
  place(
    "blr-toscano-ub-city",
    "Toscano — UB City",
    "restaurant",
    "food",
    "UB City",
    "12.9716",
    "77.5960",
    "Italian fine-dining standby of the UB City rooftop strip.",
    "Wood-fired pizzas, hand-rolled pasta, tiramisu. Brunch on Sundays. Try a window table looking onto Vittal Mallya Road.",
    { avgCostForTwo: 2500, idealMinutesAtPlace: 90, openTime: "12:00", closeTime: "23:30", popularity: 85 }
  ),
  place(
    "blr-smoke-house-deli",
    "Smoke House Deli — Indiranagar",
    "restaurant",
    "food",
    "Indiranagar 100 Feet Road",
    "12.9784",
    "77.6402",
    "European-style deli, all-day breakfasts, brown-and-cream interiors.",
    "Breakfast platters, sandwiches, wood-fired pizzas. Strong coffee. Outdoor seating that fills up on weekends.",
    { avgCostForTwo: 1600, idealMinutesAtPlace: 75, openTime: "08:00", closeTime: "23:00", popularity: 86 }
  ),
  place(
    "blr-glens-bakehouse-indiranagar",
    "Glen's Bakehouse — Indiranagar",
    "restaurant",
    "food",
    "Indiranagar",
    "12.9777",
    "77.6411",
    "Bakery + cafe — sourdough, cheesecakes, cinnamon rolls.",
    "Famous for the chocolate cake, sourdough loaves and weekday brunch. Order at the counter, sit-down area upstairs.",
    { avgCostForTwo: 900, idealMinutesAtPlace: 60, openTime: "08:30", closeTime: "23:00", popularity: 88 }
  ),
  place(
    "blr-mavalli-tiffin-indiranagar",
    "MTR — Indiranagar",
    "restaurant",
    "food",
    "Indiranagar 100 Feet Road",
    "12.9776",
    "77.6402",
    "Modernised MTR outlet — full breakfast spread + thali lunch.",
    "Convenient north-side outlet of the iconic MTR. Order the rava idli, chow chow bath and filter coffee.",
    { avgCostForTwo: 500, idealMinutesAtPlace: 60, openTime: "07:00", closeTime: "22:30", popularity: 86 }
  ),
  place(
    "blr-mainland-china-indiranagar",
    "Mainland China — Indiranagar",
    "restaurant",
    "food",
    "Indiranagar",
    "12.9764",
    "77.6402",
    "Cantonese chain favourite for dinners and group bookings.",
    "Sticky lemon chicken, hakka noodles, kung pao paneer. Old-school red lanterns, white tablecloths.",
    { avgCostForTwo: 1700, idealMinutesAtPlace: 90, openTime: "12:30", closeTime: "23:00", popularity: 80 }
  ),
  place(
    "blr-punjab-grill",
    "Punjab Grill — UB City",
    "restaurant",
    "food",
    "UB City",
    "12.9716",
    "77.5960",
    "Polished Punjabi fine-dining — dal bukhara, sigri kebabs.",
    "Tandoor-heavy menu, signature 24-hour dal. Service-led, suited for special dinners.",
    { avgCostForTwo: 2800, idealMinutesAtPlace: 90, openTime: "12:30", closeTime: "23:00", popularity: 82 }
  ),
  place(
    "blr-cafe-coffee-day-flagship",
    "Café Coffee Day — Brigade Road Flagship",
    "restaurant",
    "food",
    "Brigade Road",
    "12.9744",
    "77.6079",
    "Original CCD — the brand's first café, opened 1996.",
    "Where India's coffee café scene started. Order a Frappe and a cold-coffee with ice cream — the menu staples since day one.",
    { avgCostForTwo: 500, idealMinutesAtPlace: 60, openTime: "09:00", closeTime: "23:00", popularity: 76 }
  ),
  place(
    "blr-third-wave-coffee-koramangala",
    "Third Wave Coffee Roasters — Koramangala",
    "restaurant",
    "food",
    "Koramangala 4th Block",
    "12.9360",
    "77.6190",
    "Specialty-coffee chain that helped popularise pour-over in Bangalore.",
    "Beans from south-India estates, Aeropress, pour-over, V60. Decent food, but coffee is the reason.",
    { avgCostForTwo: 600, idealMinutesAtPlace: 60, openTime: "07:00", closeTime: "23:00", popularity: 82 }
  ),
  place(
    "blr-blue-tokai-indiranagar",
    "Blue Tokai Coffee Roasters — Indiranagar",
    "restaurant",
    "food",
    "Indiranagar",
    "12.9716",
    "77.6420",
    "Bean-to-cup roaster from Delhi — heavy filter & espresso focus.",
    "Single-origin coffees from Indian estates, batch-brew on tap, weekend tasting flights.",
    { avgCostForTwo: 700, idealMinutesAtPlace: 60, openTime: "08:00", closeTime: "22:30", popularity: 80 }
  ),
  place(
    "blr-hyderabad-biryaani-house",
    "Hyderabad Biryani House — Mosque Road",
    "restaurant",
    "food",
    "Frazer Town",
    "13.0024",
    "77.6112",
    "Kachhi-style mutton biryani — small, busy, takeaway-heavy.",
    "The original Mosque Road biryani spot. Get the mutton biryani in a half-portion plus seekh kebab.",
    { avgCostForTwo: 700, idealMinutesAtPlace: 60, openTime: "12:00", closeTime: "23:30", popularity: 86 }
  ),
  place(
    "blr-hilal-restaurant",
    "Hilal Restaurant — Frazer Town",
    "restaurant",
    "food",
    "Frazer Town",
    "13.0021",
    "77.6113",
    "Old Mosque Road eatery — paya, nahari, kebabs.",
    "Iftar specialties through Ramadan: haleem, paya, koobideh. Cash-and-paper-bills institution.",
    { avgCostForTwo: 600, idealMinutesAtPlace: 45, openTime: "11:00", closeTime: "00:00", popularity: 78 }
  ),
  place(
    "blr-asha-sweets",
    "Asha Sweets — Jayanagar",
    "restaurant",
    "food",
    "Jayanagar 4th Block",
    "12.9275",
    "77.5839",
    "Sweet shop + chaat counter — kulfi, ras malai, masala dosa.",
    "Old Jayanagar institution. Best for evening chaat and sweets to take home.",
    { avgCostForTwo: 350, idealMinutesAtPlace: 30, openTime: "08:30", closeTime: "22:00", popularity: 78 }
  ),
  place(
    "blr-anjappar-koramangala",
    "Anjappar Chettinad — Koramangala",
    "restaurant",
    "food",
    "Koramangala 5th Block",
    "12.9354",
    "77.6195",
    "Chettinad chain — mutton chukka, nattu kozhi, parotta.",
    "Spicy Chettinad mutton, country-chicken curry, fluffy parottas. Big portions; come hungry.",
    { avgCostForTwo: 900, idealMinutesAtPlace: 75, openTime: "11:00", closeTime: "23:00", popularity: 80 }
  ),
  place(
    "blr-naati-style",
    "Nagarjuna Sahakaranagar",
    "restaurant",
    "food",
    "Sahakaranagar",
    "13.0593",
    "77.5926",
    "Andhra meals on banana leaf — the north outlet.",
    "Same banana-leaf meals + biryani as the Residency Road original; less queue.",
    { avgCostForTwo: 700, idealMinutesAtPlace: 60, openTime: "11:30", closeTime: "23:00", popularity: 80 }
  ),
  place(
    "blr-mast-kalandar-koramangala",
    "Mast Kalandar — Koramangala",
    "restaurant",
    "food",
    "Koramangala 8th Block",
    "12.9261",
    "77.6306",
    "Combo-plate north-Indian thali chain.",
    "Cafeteria service; pick a combo (rajma, chole, kadhi, biryani). Quick, cheap, reliable.",
    { avgCostForTwo: 600, idealMinutesAtPlace: 45, openTime: "10:30", closeTime: "22:30", popularity: 70 }
  ),
  place(
    "blr-savoury-restaurant",
    "Savoury Restaurant — Frazer Town",
    "restaurant",
    "food",
    "Frazer Town",
    "13.0044",
    "77.6116",
    "Cosy old-school north-Indian on Mosque Road.",
    "Famous for nalli nihari and Kashmiri rogan josh. Wood panelling, slow service, family run.",
    { avgCostForTwo: 1500, idealMinutesAtPlace: 75, openTime: "12:00", closeTime: "23:00", popularity: 76 }
  ),
  place(
    "blr-rim-naam",
    "Rim Naam — The Oberoi",
    "restaurant",
    "food",
    "MG Road",
    "12.9728",
    "77.6135",
    "Award-winning Thai fine-dining in The Oberoi's gardens.",
    "Sunken seating around a koi pond, lemongrass-scented air. Tom kha gai and pla nung manao are the must-orders.",
    { avgCostForTwo: 5500, idealMinutesAtPlace: 120, openTime: "12:30", closeTime: "23:00", popularity: 85 }
  ),
  place(
    "blr-le-cirque-leela",
    "Le Cirque Signature — The Leela Palace",
    "restaurant",
    "food",
    "HAL Old Airport Road",
    "12.9603",
    "77.6500",
    "Italian-French fine dining at the Leela.",
    "Lobster cardamom, slow-braised lamb, tiramisu cigar. Reservation a must on weekends.",
    { avgCostForTwo: 7000, idealMinutesAtPlace: 120, openTime: "19:00", closeTime: "23:30", popularity: 80 }
  ),
  place(
    "blr-pllek-rooftop",
    "Hype Rooftop — Shangri-La",
    "restaurant",
    "food",
    "Vasanthnagar",
    "12.9924",
    "77.5934",
    "19th-floor rooftop bar at Shangri-La — skyline views.",
    "Best at sunset. Cocktails and small plates; weekends busy with the dinner-with-a-view crowd.",
    { avgCostForTwo: 3500, idealMinutesAtPlace: 120, openTime: "17:00", closeTime: "01:00", popularity: 80 }
  ),

  // ─────────── Pubs / breweries (10 more) ───────────
  place(
    "blr-arbor-brewing-magrath",
    "Arbor Brewing Company",
    "nightlife",
    "nightlife",
    "Magrath Road",
    "12.9716",
    "77.6097",
    "Michigan-export microbrewery — Phat Abbot Tripel, Bangalore Bliss.",
    "Eight beers on tap including Belgian Tripel, Pale Ale and seasonal stouts. Spacious central location near Brigade Road.",
    { avgCostForTwo: 2200, idealMinutesAtPlace: 150, openTime: "12:00", closeTime: "23:30", popularity: 85 }
  ),
  place(
    "blr-byg-brewski-sarjapur",
    "Byg Brewski — Sarjapur Road",
    "nightlife",
    "nightlife",
    "Sarjapur Road",
    "12.9051",
    "77.6852",
    "Sarjapur outlet of the open-air brewpub giant.",
    "Same outdoor sprawl as the Hennur original — 12 beers on tap, weekend live music.",
    { avgCostForTwo: 2000, idealMinutesAtPlace: 180, openTime: "12:00", closeTime: "23:30", popularity: 86 }
  ),
  place(
    "blr-big-pitcher",
    "Big Pitcher",
    "nightlife",
    "nightlife",
    "Old Airport Road",
    "12.9650",
    "77.6450",
    "Multi-level brewery + restaurant + Lights Camera Bar.",
    "Indoor and rooftop bars, six-screen sports lounge, separate dance floor. Resident DJs Thu-Sun.",
    { avgCostForTwo: 2000, idealMinutesAtPlace: 180, openTime: "12:00", closeTime: "01:00", popularity: 80 }
  ),
  place(
    "blr-geist-koramangala",
    "Geist Brewing Co. Taproom",
    "nightlife",
    "nightlife",
    "Koramangala 5th Block",
    "12.9343",
    "77.6232",
    "Bottled-beer brewery's tap-room with hop-forward styles.",
    "Geist's beers (Norse Witbier, Kamaraj Premium) on tap. Smaller, beer-first, no DJ.",
    { avgCostForTwo: 1500, idealMinutesAtPlace: 120, openTime: "12:00", closeTime: "23:30", popularity: 78 }
  ),
  place(
    "blr-ironhill-marathahalli",
    "Ironhill Bengaluru — Marathahalli",
    "nightlife",
    "nightlife",
    "Marathahalli",
    "12.9569",
    "77.7011",
    "Cavernous brewpub on the ORR — open dance-floor, live music.",
    "30+ thousand sqft of beer hall. Belgian Wit and Wheat are the must-tries.",
    { avgCostForTwo: 2000, idealMinutesAtPlace: 180, openTime: "12:00", closeTime: "23:30", popularity: 82 }
  ),
  place(
    "blr-1522-the-pub",
    "1522 The Pub",
    "nightlife",
    "nightlife",
    "Malleshwaram",
    "13.0083",
    "77.5701",
    "Malleshwaram's go-to weeknight pub — bar bites, beers.",
    "Sports nights and live screening of cricket / EPL. Mid-priced bar menu and chilled bottled beer.",
    { avgCostForTwo: 1500, idealMinutesAtPlace: 120, openTime: "12:00", closeTime: "23:30", popularity: 70 }
  ),
  place(
    "blr-guzzlers-inn",
    "Guzzlers Inn",
    "nightlife",
    "nightlife",
    "Rest House Road",
    "12.9716",
    "77.6066",
    "Cheap-beer dive-bar near Brigade Road — locals' favourite.",
    "Two floors, no music, ₹100-something pitcher beer. Eat at Empire across the street.",
    { avgCostForTwo: 1000, idealMinutesAtPlace: 120, openTime: "11:00", closeTime: "23:00", popularity: 75 }
  ),
  place(
    "blr-bobs-bar-indiranagar",
    "Bob's Bar — Indiranagar",
    "nightlife",
    "nightlife",
    "Indiranagar",
    "12.9776",
    "77.6391",
    "Cab-driver-pricing dive with hip décor — Indiranagar branch.",
    "Cheap beer, cheap food, '70s rock playlist. The original of the Bob's Bar mini-chain.",
    { avgCostForTwo: 900, idealMinutesAtPlace: 120, openTime: "12:00", closeTime: "23:30", popularity: 78 }
  ),
  place(
    "blr-hard-rock-cafe",
    "Hard Rock Cafe Bengaluru",
    "nightlife",
    "nightlife",
    "St Mark's Road",
    "12.9742",
    "77.5968",
    "Heritage building turned Hard Rock — live bands weekly.",
    "Housed in the 1898 Bowring Institute annexe. Burgers, ribs, and a busy live-music calendar.",
    { avgCostForTwo: 2500, idealMinutesAtPlace: 150, openTime: "12:00", closeTime: "01:00", popularity: 84 }
  ),
  place(
    "blr-high-ultra-lounge",
    "High Ultra Lounge",
    "nightlife",
    "nightlife",
    "World Trade Center",
    "13.0083",
    "77.5556",
    "31st-floor rooftop lounge — Bengaluru's highest bar.",
    "Panoramic city views, 360-degree open deck, signature cocktails. Smart-casual; come for sunset.",
    { avgCostForTwo: 3500, idealMinutesAtPlace: 150, openTime: "17:00", closeTime: "01:00", popularity: 85 }
  ),

  // ─────────── Malls & shopping centres (10 more) ───────────
  place(
    "blr-elements-mall",
    "Elements Mall",
    "mall",
    "shopping",
    "Nagawara",
    "13.0454",
    "77.6258",
    "North-Bangalore mall — Reliance Trends, Big Bazaar, INOX.",
    "Connects to Manyata's tech-park crowd. Anchor stores, INOX, busy food court.",
    { idealMinutesAtPlace: 120, openTime: "10:30", closeTime: "22:30", popularity: 72 }
  ),
  place(
    "blr-esteem-mall",
    "Esteem Mall",
    "mall",
    "shopping",
    "Hebbal",
    "13.0451",
    "77.5933",
    "Hebbal flyover-side mall — Lifestyle, Inox, hypermarket.",
    "Older mall but still anchors north Bangalore. Easy access from Hebbal junction.",
    { idealMinutesAtPlace: 120, openTime: "10:30", closeTime: "22:30", popularity: 68 }
  ),
  place(
    "blr-royal-meenakshi-mall",
    "Royal Meenakshi Mall",
    "mall",
    "shopping",
    "Bannerghatta Road",
    "12.8866",
    "77.5970",
    "South-Bangalore mall — Inox, Westside, Decathlon.",
    "Compact mall serving the Banashankari-BTM-JP Nagar belt. Westside, Inox, Decathlon and a small food court.",
    { idealMinutesAtPlace: 120, openTime: "10:30", closeTime: "22:00", popularity: 74 }
  ),
  place(
    "blr-vega-city-mall",
    "Vega City Mall",
    "mall",
    "shopping",
    "Bannerghatta Road",
    "12.8809",
    "77.5874",
    "Bannerghatta Road landmark — Shoppers Stop, Reliance Trends.",
    "Bigger than Royal Meenakshi; busy weekends. PVR cinemas, hypermarket and a 3rd-floor food court.",
    { idealMinutesAtPlace: 150, openTime: "11:00", closeTime: "22:30", popularity: 76 }
  ),
  place(
    "blr-gopalan-innovation-mall",
    "Gopalan Innovation Mall",
    "mall",
    "shopping",
    "JP Nagar Bannerghatta Road",
    "12.8916",
    "77.5933",
    "Older JP Nagar mall — INOX cinema, Big Bazaar.",
    "Frequent for the local Bannerghatta Road crowd. Mid-range fashion stores and INOX.",
    { idealMinutesAtPlace: 120, openTime: "11:00", closeTime: "22:30", popularity: 60 }
  ),
  place(
    "blr-brookefield-mall",
    "Brookefield Mall",
    "mall",
    "shopping",
    "Brookefield (Whitefield)",
    "12.9647",
    "77.7176",
    "Whitefield neighbourhood mall — fastfood floor, Cinepolis.",
    "Reliable, smaller-scale mall in Brookefield. Cinepolis cinemas, mid-range fashion.",
    { idealMinutesAtPlace: 120, openTime: "10:30", closeTime: "22:30", popularity: 72 }
  ),
  place(
    "blr-cosmos-mall-whitefield",
    "Cosmos Mall",
    "mall",
    "shopping",
    "Brookefield",
    "12.9670",
    "77.7160",
    "Casual hangout mall next to Brookefield.",
    "Mid-range stores, family restaurants, INOX. Less crowded than Phoenix Marketcity.",
    { idealMinutesAtPlace: 90, openTime: "11:00", closeTime: "22:30", popularity: 60 }
  ),
  place(
    "blr-bhartiya-mall",
    "Bhartiya Mall of Bengaluru",
    "mall",
    "shopping",
    "Thanisandra",
    "13.0732",
    "77.6360",
    "Newer Thanisandra mega-mall with INOX, PVR, food court.",
    "Anchors the Thanisandra catchment. Mix of international and Indian retail, family-friendly.",
    { idealMinutesAtPlace: 150, openTime: "11:00", closeTime: "23:00", popularity: 76 }
  ),
  place(
    "blr-lulu-global-mall",
    "Lulu Global Mall",
    "mall",
    "shopping",
    "Rajajinagar",
    "13.0150",
    "77.5500",
    "Newer mega-mall sharing the Rajajinagar / Orion catchment.",
    "Anchored by Lulu Hypermarket. Multiple cinemas, food court, family entertainment.",
    { idealMinutesAtPlace: 180, openTime: "11:00", closeTime: "23:00", popularity: 78 }
  ),
  place(
    "blr-forum-rex-walk",
    "Forum Rex Walk",
    "mall",
    "shopping",
    "Brigade Road",
    "12.9744",
    "77.6079",
    "Brigade Road's vertical mall — H&M, Levi's, Wayne's.",
    "Small but well-located right on Brigade Road. Good rest stop after a shopping walk.",
    { idealMinutesAtPlace: 60, openTime: "11:00", closeTime: "22:30", popularity: 76 }
  ),

  // ─────────── Parks / lakes (15 more) ───────────
  place(
    "blr-cariappa-memorial-park",
    "Cariappa Memorial Park",
    "park",
    "nature",
    "Cariappa Road",
    "12.9690",
    "77.6019",
    "Army-themed park with retired tanks and aircraft.",
    "Park honouring Field Marshal Cariappa. Mig-21, T-55 tank, retired naval gun on display.",
    { entryFeePerPerson: 10, idealMinutesAtPlace: 45, openTime: "08:00", closeTime: "20:00", popularity: 70 }
  ),
  place(
    "blr-indira-gandhi-musical-fountain",
    "Indira Gandhi Musical Fountain Park",
    "park",
    "nature",
    "Sankey Road",
    "12.9886",
    "77.5859",
    "Synced music + lighting fountain show in the evenings.",
    "Two shows nightly (around sunset). Kids' favourite — book in advance on weekends.",
    { entryFeePerPerson: 30, idealMinutesAtPlace: 60, openTime: "18:00", closeTime: "21:00", popularity: 70 }
  ),
  place(
    "blr-sir-mv-park",
    "Sir M Visvesvaraya Park",
    "park",
    "nature",
    "Hudson Circle",
    "12.9701",
    "77.5871",
    "Small CBD park named after Karnataka's most famous engineer.",
    "Quick green pause in the central business district.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "20:00", popularity: 55 }
  ),
  place(
    "blr-jp-narayan-park",
    "Rajiv Gandhi Park",
    "park",
    "nature",
    "Indiranagar",
    "12.9750",
    "77.6378",
    "Indiranagar's morning-walk park.",
    "Walking track, kids' play area, plant-lined paths. Quiet weekday mornings.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 30, openTime: "05:30", closeTime: "20:30", popularity: 65 }
  ),
  place(
    "blr-ranadheera-kanteerava-park",
    "Ranadheera Kanteerava Park",
    "park",
    "nature",
    "Cubbon Park area",
    "12.9774",
    "77.5925",
    "Small green strip beside the M Chinnaswamy Stadium.",
    "Hosts statues and walking paths. Often used as a meeting point before match days.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 20, openTime: "06:00", closeTime: "20:00", popularity: 55 }
  ),
  place(
    "blr-tree-park-byrasandra",
    "Tree Park Byrasandra",
    "park",
    "nature",
    "Byrasandra",
    "12.9445",
    "77.5965",
    "Mini urban forest — native trees, butterflies.",
    "BBMP biodiversity park with labelled native species. Pleasant 1-km loop trail.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "19:00", popularity: 65 }
  ),
  place(
    "blr-gkvk-botanical",
    "GKVK Botanical Garden",
    "park",
    "nature",
    "Hebbal (Agri University)",
    "13.0794",
    "77.5746",
    "University of Agricultural Sciences' green campus.",
    "200+ tree species; visitors welcome on most days. Birding hotspot.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "08:00", closeTime: "18:00", popularity: 60 }
  ),
  place(
    "blr-kadugodi-tree-park",
    "Kadugodi Tree Park",
    "park",
    "nature",
    "Kadugodi (Whitefield)",
    "12.9979",
    "77.7575",
    "Whitefield's biodiversity park.",
    "10-hectare park with walking trails and a small pond. Good for cycling.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "19:00", popularity: 60 }
  ),
  place(
    "blr-doresanipalya-forest",
    "Doresanipalya Forest Research Station",
    "park",
    "nature",
    "JP Nagar",
    "12.9020",
    "77.5854",
    "Forest Dept research campus — rare South Indian trees.",
    "75-acre research arboretum. Limited public access — call ahead. Birdwatching paradise.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "09:00", closeTime: "17:00", popularity: 55 }
  ),
  place(
    "blr-puttenahalli-yelahanka",
    "Puttenahalli Lake (Yelahanka)",
    "lake",
    "nature",
    "Yelahanka",
    "13.1023",
    "77.5942",
    "Restored north-Bangalore lake — peak pelican season Nov-Feb.",
    "Migratory bird hotspot. Painted storks, spot-billed pelicans, garganey. Walking bund and watch tower.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "18:30", popularity: 70 }
  ),
  place(
    "blr-puttenahalli-jpnagar",
    "Puttenahalli Lake (JP Nagar)",
    "lake",
    "nature",
    "JP Nagar 7th Phase",
    "12.8867",
    "77.5847",
    "Citizen-restored neighbourhood lake.",
    "Walking path, kids' park, watchtower. Active citizens' trust runs weekend birding events.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "19:00", popularity: 65 }
  ),
  place(
    "blr-jakkur-lake",
    "Jakkur Lake",
    "lake",
    "nature",
    "Jakkur",
    "13.0732",
    "77.6051",
    "North-Bangalore lake — boating, birding, treadmills.",
    "Open-air gym on the bund, paddle boats, birding gazebo. Quieter than Hebbal.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "18:30", popularity: 65 }
  ),
  place(
    "blr-agara-lake",
    "Agara Lake",
    "lake",
    "nature",
    "HSR Layout",
    "12.9243",
    "77.6451",
    "Restored 220-acre lake bordering HSR.",
    "Long walking loop, herons and storks in winter. Picnic spots on the eastern bank.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "19:00", popularity: 72 }
  ),
  place(
    "blr-hesaraghatta-lake",
    "Hesaraghatta Lake",
    "lake",
    "nature",
    "Hesaraghatta",
    "13.1376",
    "77.4847",
    "Dry-season grassland; once Bengaluru's main water source.",
    "A 1894-built reservoir on the Arkavathi. Largely dry now — adjacent grasslands are protected for the great Indian bustard's habitat history.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "19:00", popularity: 60 }
  ),
  place(
    "blr-yediyur-lake",
    "Yediyur Lake",
    "lake",
    "nature",
    "Jayanagar",
    "12.9255",
    "77.5783",
    "Small Jayanagar lake — Ganesh idol pooja venue.",
    "Compact urban lake with a temple on the western bund. Evening walkers' favourite.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 30, openTime: "06:00", closeTime: "20:00", popularity: 60 }
  ),

  // ─────────── Museums / galleries (10 more) ───────────
  place(
    "blr-venkatappa-art-gallery",
    "Venkatappa Art Gallery",
    "museum",
    "art",
    "Kasturba Road",
    "12.9742",
    "77.5985",
    "Mysore-style traditional painting + Venkatappa's works.",
    "Annexe to the Government Museum, dedicated to court painter K Venkatappa. Mysore traditional paintings and gold-leaf works.",
    { entryFeePerPerson: 20, idealMinutesAtPlace: 60, openTime: "10:00", closeTime: "17:00", openDays: "Tue-Sun", popularity: 60 }
  ),
  place(
    "blr-tasveer-gallery",
    "Tasveer Art Gallery",
    "museum",
    "art",
    "Sua House",
    "12.9678",
    "77.5990",
    "Photography-focused contemporary art gallery.",
    "India's leading photography gallery. Rotating exhibitions of Indian and international photographers.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "10:00", closeTime: "18:00", openDays: "Tue-Sun", popularity: 60 }
  ),
  place(
    "blr-sublime-galleria",
    "Sublime Galleria",
    "museum",
    "art",
    "UB City",
    "12.9716",
    "77.5960",
    "India's first sky-gallery (4th floor of UB City).",
    "Rotating contemporary art with floor-to-ceiling windows; the venue itself is a destination.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "11:00", closeTime: "21:00", popularity: 65 }
  ),
  place(
    "blr-gallery-sumukha",
    "Gallery Sumukha",
    "museum",
    "art",
    "Wilson Garden",
    "12.9530",
    "77.5938",
    "Established contemporary-art gallery — Indian + South Asian.",
    "Among Bengaluru's longest-running art galleries. Houses paintings, prints and installations.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "11:00", closeTime: "19:00", openDays: "Mon-Sat", popularity: 60 }
  ),
  place(
    "blr-vintage-car-museum",
    "Vintage Car Museum (Payana)",
    "museum",
    "art",
    "Bidadi",
    "12.7967",
    "77.3940",
    "Karnataka government's car museum on the Mysore highway.",
    "Vintage cars, two-wheelers and a small aviation section. Combines well with Innovative Film City.",
    { entryFeePerPerson: 100, idealMinutesAtPlace: 60, openTime: "10:00", closeTime: "18:00", openDays: "All", popularity: 65 }
  ),
  place(
    "blr-hmt-heritage-museum",
    "HMT Heritage Centre & Museum",
    "museum",
    "art",
    "Jalahalli",
    "13.0398",
    "77.5535",
    "Watches + machine-tools museum at the HMT factory.",
    "Showcases India's first wristwatches (Janata, Sona), Jawaharlal Nehru's gifted watches, antique milling machines.",
    { entryFeePerPerson: 30, idealMinutesAtPlace: 60, openTime: "10:00", closeTime: "17:00", openDays: "Mon-Sat", popularity: 65 }
  ),
  place(
    "blr-gandhi-bhavan",
    "Gandhi Bhavan",
    "museum",
    "art",
    "Kumara Krupa Road",
    "12.9824",
    "77.5848",
    "Library + museum on Gandhi's life and Karnataka's freedom struggle.",
    "Two galleries: Gandhi's life in photographs and Karnataka's freedom fighters. Library of original publications.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "09:00", closeTime: "17:00", openDays: "Mon-Sat", popularity: 60 }
  ),
  place(
    "blr-madras-sappers-museum",
    "Madras Sappers Museum & Archives",
    "museum",
    "art",
    "Madras Engineer Group, Ulsoor",
    "12.9542",
    "77.6040",
    "Army engineers' museum — by permit; militaria + maps.",
    "Operated by the Madras Engineer Group (MEG). Permits required in advance; staff-guided visits only.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "10:00", closeTime: "16:00", openDays: "Mon-Fri", popularity: 60 }
  ),
  place(
    "blr-philatelic-museum",
    "Philatelic Museum (GPO)",
    "museum",
    "art",
    "GPO, Cubbon Road",
    "12.9779",
    "77.5944",
    "Stamps + postal heritage at the General Post Office.",
    "Compact gallery of Indian postage history, princely-state stamps, early India Post mail bags.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "10:00", closeTime: "17:00", openDays: "Mon-Fri", popularity: 55 }
  ),
  place(
    "blr-rbi-currency-museum",
    "RBI Currency Museum",
    "museum",
    "art",
    "Nrupathunga Road",
    "12.9744",
    "77.5807",
    "RBI's small museum on Indian currency history.",
    "Coins from the Mauryan to modern era, original promissory notes, and the printing of modern banknotes.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "10:30", closeTime: "16:30", openDays: "Mon-Fri", popularity: 60 }
  ),

  // ─────────── Cultural / theatre / venues (8 more) ───────────
  place(
    "blr-ravindra-kalakshetra",
    "Ravindra Kalakshetra",
    "attraction",
    "art",
    "JC Road",
    "12.9628",
    "77.5905",
    "Government cultural hall — daily Kannada drama + dance.",
    "Built 1963 in Bengaluru's modernist style. Hosts Kannada theatre, Bharatanatyam recitals, and the annual Bengaluru International Theatre Festival.",
    { entryFeePerPerson: 200, idealMinutesAtPlace: 150, openTime: "10:00", closeTime: "22:00", popularity: 75 }
  ),
  place(
    "blr-jagriti-theatre",
    "Jagriti Theatre",
    "attraction",
    "art",
    "Whitefield (Ramagondanahalli)",
    "12.9719",
    "77.7460",
    "200-seat experimental theatre + open-air stage.",
    "Founded by Arundhati Raja. Two performance spaces. Calendar of English, Kannada and Hindi plays.",
    { entryFeePerPerson: 300, idealMinutesAtPlace: 150, openTime: "10:00", closeTime: "22:00", popularity: 75 }
  ),
  place(
    "blr-bangalore-international-centre",
    "Bangalore International Centre",
    "attraction",
    "art",
    "Domlur",
    "12.9617",
    "77.6378",
    "Open cultural hub — talks, screenings, panels.",
    "An open-architecture cultural venue. Calendar of public talks, book launches, film screenings, music.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "10:00", closeTime: "22:00", popularity: 75 }
  ),
  place(
    "blr-alliance-francaise",
    "Alliance Française de Bangalore",
    "attraction",
    "art",
    "Vasanthnagar",
    "12.9905",
    "77.5944",
    "French cultural centre — language, films, art.",
    "Library, art gallery, language classes, and a small French café. Free weekly film screenings.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "09:30", closeTime: "20:00", openDays: "Mon-Sat", popularity: 65 }
  ),
  place(
    "blr-goethe-institut",
    "Goethe-Institut / Max Mueller Bhavan",
    "attraction",
    "art",
    "Indiranagar CMH Road",
    "12.9748",
    "77.6388",
    "German cultural centre — library, films, art.",
    "Hosts German film festivals, art exhibitions and a large library. Free entry to events; pre-register where required.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "10:00", closeTime: "19:00", openDays: "Mon-Sat", popularity: 60 }
  ),
  place(
    "blr-british-council",
    "British Council Bengaluru",
    "attraction",
    "art",
    "St Mark's Road",
    "12.9728",
    "77.5957",
    "British cultural centre + library + exam centre.",
    "Lending library, English-language courses, art and literature events.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "10:30", closeTime: "19:00", openDays: "Mon-Sat", popularity: 60 }
  ),
  place(
    "blr-chinnaswamy-stadium",
    "M Chinnaswamy Stadium",
    "attraction",
    "art",
    "Cubbon Park area",
    "12.9788",
    "77.5996",
    "Royal Challengers Bengaluru's home — IPL nights are an event.",
    "Built 1969, capacity ~38,000. Karnataka Cricket Association museum on site; stadium tours bookable on non-match days.",
    { entryFeePerPerson: 300, idealMinutesAtPlace: 90, openTime: "09:00", closeTime: "18:00", popularity: 90 }
  ),
  place(
    "blr-bangalore-turf-club",
    "Bangalore Turf Club",
    "attraction",
    "art",
    "Race Course Road",
    "12.9846",
    "77.5821",
    "Heritage racecourse — race-day Saturdays Oct–Jan.",
    "Founded 1920. Race meetings on most Saturdays of the winter season; spectator stands open from 11.",
    { entryFeePerPerson: 100, idealMinutesAtPlace: 180, openTime: "11:00", closeTime: "18:00", openDays: "Sat", popularity: 65 }
  ),

  // ─────────── Heritage / landmarks (8 more) ───────────
  place(
    "blr-town-hall",
    "Sir Puttanna Chetty Town Hall",
    "attraction",
    "heritage",
    "JC Road",
    "12.9628",
    "77.5878",
    "1935 colonial town hall facing Corporation Circle.",
    "Used today for civic events and Kannada-festival gatherings. Striking Indo-Saracenic facade.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 20, openTime: "09:00", closeTime: "18:00", popularity: 60 }
  ),
  place(
    "blr-seshadri-iyer-memorial",
    "Seshadri Iyer Memorial Hall (Central Library)",
    "attraction",
    "heritage",
    "Cubbon Park",
    "12.9760",
    "77.5935",
    "Red-brick 1915 library inside Cubbon Park.",
    "Houses the State Central Library. The building's pillared red-brick frontage is one of the park's photogenic landmarks.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 30, openTime: "08:30", closeTime: "20:00", openDays: "Mon-Sat", popularity: 70 }
  ),
  place(
    "blr-raj-bhavan",
    "Raj Bhavan",
    "attraction",
    "heritage",
    "Raj Bhavan Road",
    "12.9892",
    "77.5917",
    "Governor's official residence — once Lord Cubbon's home.",
    "Wood-and-brick 1840s building with sprawling lawns. Limited public access; lawns open occasionally.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 30, openTime: "00:00", closeTime: "23:59", popularity: 60 }
  ),
  place(
    "blr-devanahalli-fort",
    "Devanahalli Fort",
    "attraction",
    "heritage",
    "Devanahalli",
    "13.2476",
    "77.7080",
    "Birthplace of Tipu Sultan — small Mughal-style fort.",
    "16th-century mud fort, later rebuilt in stone. Contains an Ayyappa shrine. Combine with airport-side eateries.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "18:00", popularity: 65 }
  ),
  place(
    "blr-begur-fort-temple",
    "Begur Panchalingeshwara Temple Site",
    "attraction",
    "heritage",
    "Begur",
    "12.8746",
    "77.6213",
    "9th-century Shiva temple with the first known inscription of 'Bengaluru'.",
    "Site of the inscription that mentions 'Bengaluru' — earliest written reference. Twin shrines from the Ganga and Chola periods.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "06:00", closeTime: "20:00", popularity: 70 }
  ),
  place(
    "blr-makalidurga-trek",
    "Makalidurga",
    "attraction",
    "heritage",
    "Doddaballapur (outskirts)",
    "13.3300",
    "77.5500",
    "Hilltop fort trek with a Shiva-Parvati shrine.",
    "1-2 hour hike to the summit fort. Continues to be a quiet alternative to Skandagiri / Nandi Hills.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 240, openTime: "06:00", closeTime: "18:00", popularity: 70 }
  ),
  place(
    "blr-nrupatunga-betta",
    "Nrupathunga Betta",
    "viewpoint",
    "nature",
    "Magadi Road",
    "12.9333",
    "77.4083",
    "Granite hill east of Savandurga with a Bahubali statue.",
    "Climb 250 steps for the 39-foot Bahubali idol and the panoramic plateau. Quiet weekday afternoons.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 120, openTime: "06:00", closeTime: "18:00", popularity: 65 }
  ),
  place(
    "blr-muddenahalli",
    "Muddenahalli (Sir M Visvesvaraya Birthplace)",
    "attraction",
    "heritage",
    "Chickballapur (outskirts)",
    "13.2700",
    "77.7400",
    "Engineer Visvesvaraya's birth home preserved as museum.",
    "The Nehru Memorial Trust-run museum holds personal artefacts of Sir M Visvesvaraya. Combine with Nandi Hills.",
    { entryFeePerPerson: 5, idealMinutesAtPlace: 45, openTime: "09:00", closeTime: "17:00", openDays: "All", popularity: 60 }
  ),

  // ─────────── Markets / shopping streets (5 more) ───────────
  place(
    "blr-malleshwaram-8th-cross",
    "Malleshwaram 8th Cross Market",
    "market",
    "shopping",
    "Malleshwaram",
    "13.0083",
    "77.5685",
    "Saturday vegetable + flower market in old Malleshwaram.",
    "Old-Bangalore feel — vegetable, flower, sweet and pooja vendors. Best 7-10 am on Saturdays.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "06:00", closeTime: "13:00", openDays: "Sat", popularity: 78 }
  ),
  place(
    "blr-jayanagar-4th-block",
    "Jayanagar 4th Block Shopping Complex",
    "market",
    "shopping",
    "Jayanagar 4th Block",
    "12.9275",
    "77.5839",
    "Open-air shopping square — sarees, sweets, electronics.",
    "Pedestrian-mall feel with surrounding lanes selling everything from silks to silver.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 90, openTime: "10:30", closeTime: "21:30", openDays: "Mon-Sun", popularity: 80 }
  ),
  place(
    "blr-avenue-road-book-market",
    "Avenue Road (Book Market)",
    "market",
    "shopping",
    "Avenue Road",
    "12.9698",
    "77.5781",
    "Wholesale book + stationery market in the heart of old Bangalore.",
    "Lined with Kannada and English bookshops, religious texts, school textbooks. Bargain hard.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 60, openTime: "10:30", closeTime: "20:00", openDays: "Mon-Sat", popularity: 78 }
  ),
  place(
    "blr-balepet-market",
    "Balepet",
    "market",
    "shopping",
    "Balepet",
    "12.9676",
    "77.5790",
    "Wholesale musical-instrument + lamp market.",
    "Best for harmoniums, tabla, brass lamps and traditional copper-ware.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "10:00", closeTime: "20:00", openDays: "Mon-Sat", popularity: 65 }
  ),
  place(
    "blr-burma-bazaar",
    "Burma Bazaar",
    "market",
    "shopping",
    "Gandhinagar",
    "12.9776",
    "77.5732",
    "Electronics + clothing flea market behind Majestic.",
    "Bargain electronics, imported clothing and household goods. Crowded; watch your wallet.",
    { entryFeePerPerson: 0, idealMinutesAtPlace: 45, openTime: "10:00", closeTime: "20:00", openDays: "Mon-Sat", popularity: 65 }
  ),

  // ─────────── Amusement / unique (10 more) ───────────
  place(
    "blr-fun-world",
    "Fun World",
    "attraction",
    "nature",
    "JC Nagar",
    "13.0233",
    "77.5944",
    "Older Bangalore amusement park — wet + dry rides.",
    "20+ rides plus a small water park. Cheaper alternative to Wonderla.",
    { entryFeePerPerson: 400, idealMinutesAtPlace: 240, openTime: "11:00", closeTime: "20:00", popularity: 70 }
  ),
  place(
    "blr-snow-city-wet",
    "Water World",
    "attraction",
    "nature",
    "JC Nagar",
    "13.0233",
    "77.5944",
    "Water park sharing the JC Nagar amusement strip.",
    "Wave pool, slides, kids' play area. Often combined with Fun World on a single ticket.",
    { entryFeePerPerson: 450, idealMinutesAtPlace: 240, openTime: "11:00", closeTime: "19:00", popularity: 65 }
  ),
  place(
    "blr-guhantara-resort",
    "Guhantara Underground Resort",
    "attraction",
    "nature",
    "Kanakapura Road",
    "12.7950",
    "77.4880",
    "India's only underground cave resort.",
    "Cave dining, themed rooms, conference halls, kid-friendly water play. Day-pass available.",
    { entryFeePerPerson: 1500, idealMinutesAtPlace: 360, openTime: "10:00", closeTime: "20:00", popularity: 70 }
  ),
  place(
    "blr-jain-farms",
    "Jain Farms",
    "attraction",
    "nature",
    "Kanakapura Road",
    "12.7400",
    "77.4960",
    "Day-out farm resort — village games, organic lunch.",
    "Bullock-cart rides, traditional gully games, archery, pottery. Lunch on a banana leaf.",
    { entryFeePerPerson: 1200, idealMinutesAtPlace: 300, openTime: "09:00", closeTime: "18:00", popularity: 70 }
  ),
  place(
    "blr-our-native-village",
    "Our Native Village",
    "attraction",
    "nature",
    "Hesaraghatta",
    "13.1500",
    "77.4900",
    "Eco-rural resort with mud houses and farm-to-table meals.",
    "Award-winning eco-resort. Mud-walled cottages, biogas, organic farm tours. Best as a day or overnight reset.",
    { entryFeePerPerson: 2500, idealMinutesAtPlace: 360, openTime: "08:00", closeTime: "20:00", popularity: 72 }
  ),
  place(
    "blr-mango-mist-resort",
    "Mango Mist Resort",
    "attraction",
    "nature",
    "Bagaluru, north Bangalore",
    "13.1500",
    "77.6500",
    "Family resort with pools and 50 acres of mango orchards.",
    "Indoor and outdoor pools, ATV rides, kids' play, in-season mango harvest tours (May-Jun).",
    { entryFeePerPerson: 1300, idealMinutesAtPlace: 360, openTime: "10:00", closeTime: "19:00", popularity: 68 }
  ),
  place(
    "blr-play-arena",
    "Play Arena",
    "attraction",
    "nature",
    "Sarjapur Road",
    "12.9080",
    "77.6810",
    "Family-fun centre — pool, paintball, bowling, go-karts.",
    "Indoor + outdoor activity park aimed at families and small groups. Day-pass covers most activities.",
    { entryFeePerPerson: 950, idealMinutesAtPlace: 240, openTime: "10:00", closeTime: "22:00", popularity: 78 }
  ),
  place(
    "blr-torq03-paintball",
    "Torq03 Adventure Park",
    "attraction",
    "nature",
    "Marathahalli",
    "12.9569",
    "77.7011",
    "Indoor paintball, go-karting, bowling.",
    "Compact urban adventure park with paintball arenas, karts and laser tag. Birthday-party favourite.",
    { entryFeePerPerson: 750, idealMinutesAtPlace: 180, openTime: "11:00", closeTime: "23:00", popularity: 65 }
  ),
  place(
    "blr-red-rider-sports",
    "Red Rider Sports Arena",
    "attraction",
    "nature",
    "Hennur Road",
    "13.0400",
    "77.6500",
    "Cricket nets, football pitches, badminton courts.",
    "Pay-per-hour bookings on AstroTurf pitches, box cricket, badminton, table tennis.",
    { entryFeePerPerson: 500, idealMinutesAtPlace: 120, openTime: "06:00", closeTime: "23:00", popularity: 70 }
  ),
  place(
    "blr-aquarium-cubbon",
    "Bangalore Aquarium",
    "museum",
    "art",
    "Cubbon Park",
    "12.9770",
    "77.5933",
    "Small public aquarium inside Cubbon Park.",
    "India's second-oldest aquarium (1983). 70+ varieties of fresh-water fish. 30-min visit.",
    { entryFeePerPerson: 10, idealMinutesAtPlace: 30, openTime: "10:00", closeTime: "17:30", openDays: "Tue-Sun", popularity: 60 }
  ),

  // ─────────── Restaurants — bonus 8 ───────────
  place(
    "blr-burma-burma-uvb-mall",
    "Toscano — Phoenix Marketcity",
    "restaurant",
    "food",
    "Whitefield",
    "12.9959",
    "77.6967",
    "Toscano's east-Bangalore Italian outlet.",
    "Same wood-fired oven menu as the UB City flagship. Convenient if you're already at the mall.",
    { avgCostForTwo: 2500, idealMinutesAtPlace: 90, openTime: "12:00", closeTime: "23:00", popularity: 78 }
  ),
  place(
    "blr-paradise-biryani",
    "Paradise Biryani — Indiranagar",
    "restaurant",
    "food",
    "Indiranagar",
    "12.9776",
    "77.6395",
    "Hyderabad's Paradise biryani chain — kachhi mutton biryani.",
    "The Bengaluru branch of Hyderabad's storied biryani house. Mutton kachhi biryani is the order.",
    { avgCostForTwo: 1100, idealMinutesAtPlace: 60, openTime: "11:30", closeTime: "23:30", popularity: 84 }
  ),
  place(
    "blr-shivaji-military",
    "Shivaji Military Hotel",
    "restaurant",
    "food",
    "Jayanagar 9th Block",
    "12.9100",
    "77.5896",
    "Sunday-only mutton donne biryani — a Bengaluru cult.",
    "Open Sundays only (and Sat afternoons depending on prep). Mutton biryani served in a donne (palm-leaf cone).",
    { avgCostForTwo: 600, idealMinutesAtPlace: 45, openTime: "12:00", closeTime: "16:00", openDays: "Sat-Sun", popularity: 88 }
  ),
  place(
    "blr-rameshwaram-cafe",
    "Rameshwaram Cafe",
    "restaurant",
    "food",
    "Sahakar Nagar",
    "13.0680",
    "77.5800",
    "Modern Tam-Bram café — ghee podi idli, filter coffee.",
    "Counter service, lightning-fast turnover. Try the podi idli and rava kesari.",
    { avgCostForTwo: 350, idealMinutesAtPlace: 30, openTime: "07:00", closeTime: "22:00", popularity: 88 }
  ),
  place(
    "blr-puliyogare-point",
    "Puliyogare Point",
    "restaurant",
    "food",
    "Basavanagudi",
    "12.9422",
    "77.5673",
    "Tamarind rice + curd rice — Basavanagudi standing institution.",
    "Eat-in-hand puliyogare since 1968. Cash only, queue at the counter.",
    { avgCostForTwo: 150, idealMinutesAtPlace: 20, openTime: "07:00", closeTime: "21:00", popularity: 78 }
  ),
  place(
    "blr-koshys-jewel-box",
    "The Jewel Box (Koshy's)",
    "restaurant",
    "food",
    "St Mark's Road",
    "12.9728",
    "77.5959",
    "Bar side of Koshy's — strong drinks, jazz playlist.",
    "The atmospheric inner room of Koshy's; black-and-white tiled floor, vinyl on the speakers.",
    { avgCostForTwo: 1500, idealMinutesAtPlace: 120, openTime: "11:00", closeTime: "23:30", popularity: 86 }
  ),
  place(
    "blr-cafe-konark",
    "Cafe Konark",
    "restaurant",
    "food",
    "JC Road",
    "12.9606",
    "77.5860",
    "Old-school dosa + omelette parlour near Town Hall.",
    "Open since the 1960s. Excellent benne masala dosa, butter-roast, and the ghee chowchow bath.",
    { avgCostForTwo: 250, idealMinutesAtPlace: 30, openTime: "07:00", closeTime: "22:00", popularity: 78 }
  ),
  place(
    "blr-kc-das",
    "K C Das",
    "restaurant",
    "food",
    "Church Street",
    "12.9742",
    "77.6075",
    "Original Kolkata rasgulla — Bangalore Church Street branch.",
    "Rasgulla, raj bhog, mishti doi from the inventor's family business. Standing counter service.",
    { avgCostForTwo: 250, idealMinutesAtPlace: 30, openTime: "08:00", closeTime: "22:00", popularity: 78 }
  ),
];
