CREATE TABLE IF NOT EXISTS "city_places" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" varchar(140) NOT NULL,
	"name" varchar(200) NOT NULL,
	"city" varchar(80) NOT NULL,
	"kind" varchar(40) NOT NULL,
	"category" varchar(40) NOT NULL,
	"area" varchar(120),
	"description" text NOT NULL,
	"short_description" varchar(240) NOT NULL,
	"image_url" text,
	"entry_fee_per_person" integer DEFAULT 0 NOT NULL,
	"avg_cost_for_two" integer,
	"ideal_minutes_at_place" integer DEFAULT 60 NOT NULL,
	"open_time" varchar(10),
	"close_time" varchar(10),
	"open_days" varchar(30),
	"tags" text,
	"latitude" varchar(20) NOT NULL,
	"longitude" varchar(20) NOT NULL,
	"google_place_id" text,
	"popularity" integer DEFAULT 50 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "city_places_slug_unique" UNIQUE("slug")
);
